### ISSUE TITLE
Hey wheres the 1.19.2 download file

### ISSUE THREAD

**Issue by RVxScreenedTwo** [SiverDX/cave_dweller#1]
cant seem to find the correct jar file for cave dweller 1.19.2

**Comment by SiverDX** [comment]
last github release is here https://github.com/SiverDX/cave_dweller/releases
curseforge is being reviewed

**Comment by RVxScreenedTwo** [comment]
why is the name of the file for 1.2.1 if the github is for 1.19.2

**Comment by SiverDX** [comment]
because its the version of this mod not the mc version
