### ISSUE TITLE
climbing causes problems

### ISSUE THREAD

**Issue by ScaredSkeleton23** [SiverDX/cave_dweller#11]
when the cave dweller is chasing, climbing can cause it to get stuck and not crawl/crouch, instead just standing at the end of the lower roof, sometimes it works as normal though.

**Comment by SiverDX** [comment]
Fixed an issue with a certain situation just now
~Which version are you on?~ nvm just saw you're on 1.20

**Comment by SiverDX** [comment]
Can you try this version?

https://github.com/SiverDX/cave_dweller/releases/tag/test_build-1.20.1-1.6.3

**Comment by ScaredSkeleton23** [comment]
seems to work well for the most part, but the dwellers can't go through a 1x1 hole if it's in the middle of a 3x3

after further testing, they can get out if they climb the right way, because then it's below them and those work fine

**Comment by SiverDX** [comment]
https://github.com/SiverDX/cave_dweller/releases/tag/test_build-1.20.1-1.6.4 should have a fix  for that
also it no longer avoids rails for pathfinding

**Comment by SiverDX** [comment]
Latest CurseForge release (1.6.4) fixes some issues with pathfinding and crawl/crouch
