### ISSUE TITLE
Sounds are global

### ISSUE THREAD

**Issue by leftbones** [SiverDX/cave_dweller#12]
For some reason on my server running 1.19.2, if one person is being stalked by the Cave Dweller, everyone on the server can hear the noises as if he is right next to you. Makes it too annoying to be usable.

**Comment by SiverDX** [comment]
Are you referring to the chase sound?

Or the ambient noises? Those are currently played to all potential targets (which is intended)
Potential target meaning they fit the criteria for the cave dweller to spawn at

**Comment by leftbones** [comment]
I’m referring to the cave noises specific to the cave dweller, indicating he’s drawing near. When it was happening, one of the players on my server was in a cave (valid) another was on the surface near the base (invalid) and I was in a forest (invalid), also thousands of blocks apart, yet we could all hear the noises. They were happening every 10 seconds or so.

On Oct 13, 2023, at 12:31 AM, SiverDX ***@***.***> wrote:

﻿

Are you referring to the chase sound?

Or the ambient noises? Those are currently played to all potential targets (which is intended)
Potential target meaning they fit the criteria for the cave dweller to spawn at

**Comment by SiverDX** [comment]
Are you using the latest version?

You must have changed some configs then
1. The noise doesn't happen that often by default
2. It is possible to modify where the cave dweller can spawn (surface, biomes, etc.)

I cannot reproduce this issue (on a server) with the default configs
