### ISSUE TITLE
[1.18.2] Crash when spawning Cave Dweller using Forge 40.1.0

### ISSUE THREAD

**Issue by ConqAra** [SiverDX/cave_dweller#14]
Mod Conflict?
Log: [https://mclo.gs/RDljjkz](https://mclo.gs/RDljjkz)

**Comment by ConqAra** [comment]
Wasn't armorcurve or quark. Still trying to find out if there's a conflict. I don't know why it's crashing when I try to spawn the cave dweller with its spawn egg

**Comment by SiverDX** [comment]
Try using Forge `40.1.16` or later
It seems earlier versions didn't have the step height attribute / kept adding and removing it

In general it's recommended to use the latest / stable forge version due to various bug fixes

**Comment by ConqAra** [comment]
That fixed it, thanks
