### ISSUE TITLE
[1.18.2] Crash again with cave dweller naturally spawning in Forge 40.1.36 or below

### ISSUE THREAD

**Issue by ConqAra** [SiverDX/cave_dweller#15]
log: [https://mclo.gs/W7Lk2e9](https://mclo.gs/W7Lk2e9)

I don't understand, now it crashes when naturally spawning or making noise. 
I'm on forge 40.1.16

**Comment by ConqAra** [comment]
changed to forge 40.1.54 and it stopped crashing. odd?

**Comment by SiverDX** [comment]
seems like biome tags were introduced in 40.1.37
