### ISSUE TITLE
Animation issues

### ISSUE THREAD

**Issue by Scarecrow356** [SiverDX/cave_dweller#17]
I downloaded the 1.20.1 version for this mod from curseforge, and put it into a custom modpack I made. all of the animations don't seem to work, I have geckolib, but I don't know why the animations aren't working, could I get some help?

**Comment by SiverDX** [comment]
geckolib animations may break with shaders / optifine
for shaders you can try to disable entity shadows

**Comment by Scarecrow356** [comment]
> geckolib animations may break with shaders / optifine for shaders you can try to disable entity shadows

I'll try that rn

**Comment by Scarecrow356** [comment]
> > geckolib animations may break with shaders / optifine for shaders you can try to disable entity shadows
> 
> I'll try that rn

I fixed the issue, switched the shaderpack. Thank you!!
