### ISSUE TITLE
Cave Dweller Issues

### ISSUE THREAD

**Issue by StarWill01** [SiverDX/cave_dweller#2]
Hello! I downloaded the 1.19.2 version of your ported mod but the issue is that the entity does not do anything, no sound effects, does not spawn normally, anything like the original 1.19.3 mod. How do I fix this issue?

**Comment by SiverDX** [comment]
https://minecrafthopper.net/help/guides/getting-minecraft-latest-log/

Also make sure you're using a Forge modding instance and the timers are not set too high if you've modified them

**Comment by StarWill01** [comment]
I have not modified anything to the code and I am using forge, the issue is the cave dweller is not active, when I enter a cave there are no sound effects or anything that shows he is there. Spawning him in with an egg works but not in survival.

**Comment by StarWill01** [comment]
If it has something to do with the timer and it taking to long to start, where in the file is that?

**Comment by SiverDX** [comment]
Timers can be configured in the server config
The spawn timer by default can be between 5 - 10 minutes with a 40 % chance of it being 20 minutes

**Comment by StarWill01** [comment]
![image_2023-07-25_171302143](https://github.com/SiverDX/cave_dweller/assets/137447292/c6939528-a225-4754-bcbe-c075cacb9e28)
So I found the ServerConfig but I am not sure where the code is for the timer.

**Comment by StarWill01** [comment]
I want to make it the same as the original mod but I am not sure which number I would switch it to.

**Comment by SiverDX** [comment]
the serverconfig located in your world directory, its a .toml file

![image](https://github.com/SiverDX/cave_dweller/assets/22003703/99bd956c-fa4b-4bff-9170-f23d454f9642)

Original:
Spawn timer: 480 - 1080 seconds with a chance of 800 - 1600 seconds (for nightmare you basically just remove a 0)
Noise timer: 100 - 180 seconds

**Comment by StarWill01** [comment]
![image](https://github.com/SiverDX/cave_dweller/assets/137447292/cb1718fb-fb23-4714-893a-975b9a695831)
Would this be good?

**Comment by StarWill01** [comment]
I want to have it spawn frequently and make noises very often

**Comment by SiverDX** [comment]
The # lines are comments and tell you what that config option is and which values you can pick
You need to edit the line below those comments

**Comment by StarWill01** [comment]
Oh alright, that makes a lot more sense. To make it just like the cavenoise-nightmare, would I just change the numbers under reset_calm_min, reset_calm_max, reset_calm_cooldown_chance, reset_calm_cooldown and also the sound timers to remove a zero (300 would be 30)? I recall you stating that above^

**Comment by StarWill01** [comment]
![image](https://github.com/SiverDX/cave_dweller/assets/137447292/8195dd28-6efd-440d-856e-3b3814ea6f3b)

**Comment by SiverDX** [comment]
yes those are the timers
removing a 0 was about the original timers, i used slightly different ones
e.g. 5-10 minutes instead of 8-18

**Comment by SiverDX** [comment]
Seems to be done
