### ISSUE TITLE
Spawning Broken when config changed

### ISSUE THREAD

**Issue by PenguCCN** [SiverDX/cave_dweller#6]
Attempted to edit the config to allow the dweller to spawn on the surface and instead it completely bricks the mod.

Also when restarting the server the config gets overwritten to default.
![image](https://github.com/SiverDX/cave_dweller/assets/86432003/834e3549-a8a4-490d-8b56-a1fb5dd28fb3)

**Comment by SiverDX** [comment]
Can you post your `latest.log` when this occurs?

Also how are you configuring the mod
- Edit the file manually (do you have auto-save?)
- Some ingame mod configuration (e.g. `Configured`)
- Some third-party server tool?
