### ISSUE TITLE
Is this for fabric?

### ISSUE THREAD

**Issue by Ricenami** [SiverDX/cave_dweller#7]
Sorry if this is a dumb question, but im not sure if this is for fabric or forge. I added the mod to my modpack, and it's not showing up. I have geckolib, and I don't have the original mod installed.

**Comment by SiverDX** [comment]
The mod is for forge

If the cave dweller does not spawn you can try to reduce the timer in the config or summon it through a command to check if its properly installed

**Comment by Ricenami** [comment]
Thanks for the quick response! I'm running a fabric modpack so I'll have to use the 'orignal' mod instead, although I'm not sure if the original mod works in multiplayer

**Comment by SiverDX** [comment]
The original is also for Forge

You should look into one of these:
https://github.com/SiverDX/cave_dweller/issues/8
