### ISSUE TITLE
Can you also port the fabric version for 1.18.2?

### ISSUE THREAD

**Issue by ConqAra** [SiverDX/cave_dweller#8]
I saw a 1.18.2 for the forge version, figure I'd request for a 1.18.2 release for the fabric if you don't mind doing that!

**Comment by SiverDX** [comment]
I don't plan on doing Fabric, you'll have to ask the maintainers of the Farbic version for that
- https://www.curseforge.com/minecraft/mc-mods/cave-dweller-fabric
- https://modrinth.com/mod/cave-dweller-evolved-(fabric)

**Comment by ConqAra** [comment]
Oh what? The fabric version on modrinth literally lead me here when I clicked 'source' that's so weird
