### ISSUE TITLE
crash upon ticking behaviour

### ISSUE THREAD

**Issue by AGmukbooks** [SiverDX/cave_dweller#9]
repeatable issue, cave dwellar engages in hostility, and when LOS is broken he stops ticking and crashes the user

providing log here. 

[crash-2023-09-22_10.51.35-client.txt](https://github.com/SiverDX/cave_dweller/files/12702538/crash-2023-09-22_10.51.35-client.txt)

**Comment by SiverDX** [comment]
Can you test it with https://github.com/SiverDX/cave_dweller/releases/tag/test_build-1.19.2-1.6.2

In theory the timer should not be null, you can try to re-create the issue and then send your `debug.log`

**Comment by AGmukbooks** [comment]
will do. i'll have this tested by tomorrow

**Comment by AGmukbooks** [comment]
addendum! he's fine now! if i run into another issue i'll tell you imidiately, the test file  was a great success

**Comment by SiverDX** [comment]
Latest version is now uploaded on CurseForge
